### ISSUE TITLE
Improve polynomial interpolation

### ISSUE THREAD

**Issue by brech1** [brech1/keaki#12]
# Description

As suggested by @RiverRuby 

We could improve performance on polynomial interpolation by using pre-calculated lagrange basis polynomials to execute it.

**Comment by mahmudsudo** [comment]
i am personally interested in this performance improvement on polynomial interpolation, can i take on this issue ?

**Comment by brech1** [comment]
Hey hey, thank you for your interest on this! Unfortunately I'm already working on this issue at the moment and my next PR will include it
